"""tamper scenarios

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-04 13:40:49.983705

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tamper_scenarios",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("scenario_type", sa.Text(), nullable=False),
        sa.Column("attacker_model", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("source_stream_id", sa.UUID(), nullable=False),
        sa.Column("lab_stream_id", sa.UUID(), nullable=False),
        sa.Column("parameters", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("expected_detected", sa.Boolean(), nullable=False),
        sa.Column("true_first_index", sa.BigInteger(), nullable=True),
        sa.Column("verification_run_id", sa.UUID(), nullable=True),
        sa.Column("actual_detected", sa.Boolean(), nullable=True),
        sa.Column("first_failure_index", sa.BigInteger(), nullable=True),
        sa.Column("first_failure_check", sa.Text(), nullable=True),
        sa.Column("located_correctly", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["lab_stream_id"],
            ["log_streams.id"],
            name=op.f("fk_tamper_scenarios_lab_stream_id_log_streams"),
        ),
        sa.ForeignKeyConstraint(
            ["source_stream_id"],
            ["log_streams.id"],
            name=op.f("fk_tamper_scenarios_source_stream_id_log_streams"),
        ),
        sa.ForeignKeyConstraint(
            ["verification_run_id"],
            ["verification_runs.id"],
            name=op.f("fk_tamper_scenarios_verification_run_id_verification_runs"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tamper_scenarios")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tamper_scenarios")
    # ### end Alembic commands ###
