"""batches and verification runs

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-04 13:16:10.310512

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "batches",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("stream_id", sa.UUID(), nullable=False),
        sa.Column("batch_index", sa.Integer(), nullable=False),
        sa.Column("first_chain_index", sa.BigInteger(), nullable=False),
        sa.Column("last_chain_index", sa.BigInteger(), nullable=False),
        sa.Column("leaf_count", sa.Integer(), nullable=False),
        sa.Column("merkle_root", sa.LargeBinary(), nullable=False),
        sa.Column(
            "sealed_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint(
            "leaf_count = last_chain_index - first_chain_index + 1",
            name=op.f("ck_batches_leaf_count_matches"),
        ),
        sa.CheckConstraint("octet_length(merkle_root) = 32", name=op.f("ck_batches_root_length")),
        sa.ForeignKeyConstraint(
            ["stream_id"], ["log_streams.id"], name=op.f("fk_batches_stream_id_log_streams")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_batches")),
        sa.UniqueConstraint("stream_id", "batch_index", name=op.f("uq_batches_stream_id")),
    )
    op.create_table(
        "verification_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("stream_id", sa.UUID(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("duration_ms", sa.Float(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("first_failing_batch_id", sa.UUID(), nullable=True),
        sa.Column("first_failing_chain_index", sa.BigInteger(), nullable=True),
        sa.Column("first_failed_check", sa.Text(), nullable=True),
        sa.Column("records_checked", sa.BigInteger(), nullable=False),
        sa.Column("unbatched_records", sa.BigInteger(), nullable=False),
        sa.Column("rules_version", sa.Text(), nullable=False),
        sa.Column("triggered_by", sa.UUID(), nullable=True),
        sa.Column("report", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint(
            "status IN ('VALID', 'TAMPERING_DETECTED', 'ERROR')",
            name=op.f("ck_verification_runs_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["stream_id"],
            ["log_streams.id"],
            name=op.f("fk_verification_runs_stream_id_log_streams"),
        ),
        sa.ForeignKeyConstraint(
            ["triggered_by"],
            ["operators.id"],
            name=op.f("fk_verification_runs_triggered_by_operators"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_verification_runs")),
    )
    op.create_table(
        "verification_findings",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("chain_index", sa.BigInteger(), nullable=True),
        sa.Column("batch_id", sa.UUID(), nullable=True),
        sa.Column("check_name", sa.Text(), nullable=False),
        sa.Column("expected", sa.Text(), nullable=False),
        sa.Column("actual", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["verification_runs.id"],
            name=op.f("fk_verification_findings_run_id_verification_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_verification_findings")),
    )
    op.create_index(
        op.f("ix_verification_findings_run_id"), "verification_findings", ["run_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_verification_findings_run_id"), table_name="verification_findings")
    op.drop_table("verification_findings")
    op.drop_table("verification_runs")
    op.drop_table("batches")
    # ### end Alembic commands ###
