/** Small shared UI pieces. */

import { useEffect, useState, type ReactNode } from "react";
import { errorMessage } from "./api/client";
import type { StreamKind } from "./api/types";

export function KindBadge({ kind }: { kind: StreamKind }) {
  const label = { primary: "PRIMARY", synthetic: "SYNTHETIC DATA", lab: "LAB DATA (TAMPERED COPY)" }[kind];
  return <span className={`badge kind-${kind}`}>{label}</span>;
}

/** Shown on every synthetic/lab stream page so test data is never mistaken for evidence. */
export function DataBanner({ kind }: { kind: StreamKind }) {
  if (kind === "primary") return null;
  return (
    <div className={`banner kind-${kind}`} role="note">
      {kind === "synthetic"
        ? "Synthetic data generated by the workload generator — not genuine audit evidence."
        : "Lab clone used for controlled tampering experiments — this data has been deliberately modified."}
    </div>
  );
}

export function StatusBadge({ status }: { status: string | null | undefined }) {
  if (!status) return <span className="badge muted">not verified</span>;
  const tone = status === "VALID" ? "ok" : "bad";
  return <span className={`badge ${tone}`}>{status === "TAMPERING_DETECTED" ? "TAMPERING DETECTED" : status}</span>;
}

export function Check({ ok, label }: { ok: boolean | null | undefined; label?: string }) {
  if (ok === null || ok === undefined) return <span className="muted">—</span>;
  return <span className={ok ? "status ok" : "status bad"}>{ok ? "✓" : "✗"} {label}</span>;
}

export function Hash({ value, full = false }: { value: string | null | undefined; full?: boolean }) {
  if (!value) return <span className="muted">—</span>;
  return (
    <code className="hash" title={value}>
      {full ? value : `${value.slice(0, 12)}…${value.slice(-6)}`}
    </code>
  );
}

export function ErrorBox({ error }: { error: unknown }) {
  if (!error) return null;
  return (
    <div className="error" role="alert">
      {errorMessage(error)}
    </div>
  );
}

export function Card({ title, actions, children }: { title?: string; actions?: ReactNode; children: ReactNode }) {
  return (
    <section className="card">
      {(title || actions) && (
        <header className="card-header">
          {title && <h2>{title}</h2>}
          {actions}
        </header>
      )}
      {children}
    </section>
  );
}

export function formatTime(iso: string): string {
  const d = new Date(iso);
  return Number.isNaN(d.getTime()) ? iso : d.toISOString().replace("T", " ").replace("Z", " UTC");
}

/** Run an async loader; returns data, error, loading flag and a reload function. */
export function useLoader<T>(load: () => Promise<T>, deps: unknown[]) {
  const [state, setState] = useState<{ data?: T; error?: unknown; loading: boolean }>({ loading: true });
  const [tick, setTick] = useState(0);
  useEffect(() => {
    let cancelled = false;
    setState((s) => ({ ...s, loading: true }));
    load()
      .then((data) => !cancelled && setState({ data, loading: false }))
      .catch((error) => !cancelled && setState({ error, loading: false }));
    return () => {
      cancelled = true;
    };
  }, [...deps, tick]);
  return { ...state, reload: () => setTick((t) => t + 1) };
}
