/** Compatibility layer: the original audit/research pages import these names. They now render
 *  design-system components (src/ui), so those pages get the new look without logic changes. */

import { useEffect, useState, type ReactNode } from "react";
import type { StreamKind } from "./api/types";
import { KindBadge as UiKindBadge, PassFail, VerificationBadge } from "./ui/badges";
import { ErrorState, HashText, Panel } from "./ui/primitives";

export function KindBadge({ kind }: { kind: StreamKind }) {
  return <UiKindBadge kind={kind} />;
}

/** Shown on every synthetic/lab stream page so test data is never mistaken for evidence. */
export function DataBanner({ kind }: { kind: StreamKind }) {
  if (kind === "primary") return null;
  return (
    <div className={`banner kind-${kind}`} role="note">
      {kind === "synthetic"
        ? "Synthetic data generated by the workload generator — not genuine audit evidence."
        : "Lab clone used for controlled tampering experiments — this data has been deliberately modified."}
    </div>
  );
}

export function StatusBadge({ status }: { status: string | null | undefined }) {
  return <VerificationBadge status={status} />;
}

export function Check({ ok, label }: { ok: boolean | null | undefined; label?: string }) {
  return <PassFail ok={ok} pass={label ?? "PASS"} fail={label ?? "FAIL"} />;
}

export function Hash({ value, full = false }: { value: string | null | undefined; full?: boolean }) {
  return <HashText value={value} full={full} />;
}

export function ErrorBox({ error }: { error: unknown }) {
  return <ErrorState error={error} />;
}

export function Card({ title, actions, children }: { title?: string; actions?: ReactNode; children: ReactNode }) {
  return (
    <Panel title={title} actions={actions}>
      {children}
    </Panel>
  );
}

export function formatTime(iso: string): string {
  const d = new Date(iso);
  return Number.isNaN(d.getTime()) ? iso : d.toISOString().replace("T", " ").replace("Z", " UTC");
}

/** Run an async loader; returns data, error, loading flag and a reload function. */
export function useLoader<T>(load: () => Promise<T>, deps: unknown[]) {
  const [state, setState] = useState<{ data?: T; error?: unknown; loading: boolean }>({ loading: true });
  const [tick, setTick] = useState(0);
  useEffect(() => {
    let cancelled = false;
    setState((s) => ({ ...s, loading: true }));
    load()
      .then((data) => !cancelled && setState({ data, loading: false }))
      .catch((error) => !cancelled && setState({ error, loading: false }));
    return () => {
      cancelled = true;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [...deps, tick]);
  return { ...state, reload: () => setTick((t) => t + 1) };
}
